export const DISORDERS = [
  {
    slug: "stroke-treatment",
    title: "Stroke Management",
    icon: "Activity",
    shortDesc: "Emergency and long-term stroke care with rapid response.",
    color: "red",
    priority: true,
  },
  {
    slug: "epilepsy-treatment",
    title: "Epilepsy / Seizure Care",
    icon: "Zap",
    shortDesc: "Advanced seizure monitoring with Video EEG technology.",
    color: "amber",
    priority: true,
  },
  {
    slug: "paralysis-treatment",
    title: "Paralysis Treatment",
    icon: "PersonStanding",
    shortDesc: "Comprehensive motor recovery and rehabilitation programs.",
    color: "blue",
    priority: false,
  },
  {
    slug: "migraine-treatment",
    title: "Migraine & Headaches",
    icon: "Brain",
    shortDesc:
      "Evidence-based treatment for chronic migraine and headache disorders.",
    color: "purple",
    priority: false,
  },
  {
    slug: "memory-loss-treatment",
    title: "Memory Loss / Dementia",
    icon: "CircleDot",
    shortDesc: "Early diagnosis and management of memory disorders.",
    color: "teal",
    priority: false,
  },
  {
    slug: "vertigo-treatment",
    title: "Dizziness & Vertigo",
    icon: "Compass",
    shortDesc: "Accurate vestibular assessment and vertigo management.",
    color: "indigo",
    priority: false,
  },
  {
    slug: "neuropathy-treatment",
    title: "Neuropathy & Nerve Weakness",
    icon: "Waves",
    shortDesc: "ENMG-guided diagnosis of peripheral nerve disorders.",
    color: "cyan",
    priority: false,
  },
  {
    slug: "spinal-disorders",
    title: "Spinal & Back Disorders",
    icon: "Link",
    shortDesc:
      "Non-surgical management of neck pain, back pain, and spinal conditions.",
    color: "orange",
    priority: false,
  },
  {
    slug: "",
    title: "Numbness in Arms & Legs",
    icon: "Hand",
    shortDesc: "Assessment of sensory disturbances and nerve compression.",
    color: "gray",
    priority: false,
  },
  {
    slug: "",
    title: "Hearing Loss (Neurological)",
    icon: "Ear",
    shortDesc: "Neuro-otological evaluation of sensorineural hearing loss.",
    color: "gray",
    priority: false,
  },
  {
    slug: "",
    title: "Chronic Neurological Diseases",
    icon: "HeartPulse",
    shortDesc:
      "Long-term management of Parkinson's, MS, and chronic conditions.",
    color: "gray",
    priority: false,
  },
  {
    slug: "",
    title: "Neck & Cervical Pain",
    icon: "Bone",
    shortDesc: "Cervical disc disease and nerve root compression treatment.",
    color: "gray",
    priority: false,
  },
];

export const DIAGNOSTICS = [
  {
    id: "video-eeg",
    title: "Video EEG",
    icon: "BrainCircuit",
    desc: "Advanced brain wave monitoring with simultaneous video recording for precise seizure localization and epilepsy classification.",
    badge: "Advanced",
    featured: true,
  },
  {
    id: "enmg",
    title: "ENMG",
    icon: "Waves",
    desc: "Electroneuromyography for comprehensive peripheral nerve conduction and muscle function assessment — diagnosing neuropathy and myopathy.",
    badge: "Specialized",
    featured: true,
  },
  {
    id: "laboratory",
    title: "Laboratory Services",
    icon: "FlaskConical",
    desc: "Full in-house diagnostic lab with rapid turnaround for complete blood workup, cerebrospinal fluid analysis, and specialized neuro markers.",
    badge: "In-House",
    featured: false,
  },
  {
    id: "ecg",
    title: "ECG",
    icon: "HeartPulse",
    desc: "Cardiac rhythm evaluation essential for stroke risk stratification, syncope investigation, and neurological monitoring.",
    badge: "Cardiac Support",
    featured: false,
  },
  {
    id: "digital-xray",
    title: "Digital X-Ray",
    icon: "ScanLine",
    desc: "High-resolution digital imaging for cervical and lumbar spine, skull, and structural neurological assessment with instant results.",
    badge: "Same Day",
    featured: false,
  },
];

export const SERVICES = [
  "Neurology Consultation",
  "Stroke Treatment",
  "Epilepsy / Seizure Care",
  "Migraine Treatment",
  "Paralysis Treatment",
  "Memory / Dementia Assessment",
  "Vertigo / Dizziness Treatment",
  "Neuropathy / Nerve Weakness",
  "Spinal & Back Disorders",
  "Neuro Rehabilitation",
  "Video EEG",
  "ENMG Testing",
];
